import { createContext, useContext, useState, ReactNode, useCallback } from "react";

type Lang = "de" | "en";

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<Lang, string>> = {
  // Navbar
  "nav.problem": { de: "DAS PROBLEM", en: "THE PROBLEM" },
  "nav.services": { de: "SERVICES", en: "SERVICES" },
  "nav.nis2": { de: "NIS-2", en: "NIS-2" },
  "nav.videos": { de: "VIDEOS", en: "VIDEOS" },
  "nav.preise": { de: "PREISE", en: "PRICING" },
  "nav.kontakt": { de: "KONTAKT", en: "CONTACT" },
  "nav.cta": { de: "AUFWACHEN", en: "WAKE UP" },

  // Hero
  "hero.spoiler": { de: "SPOILER: SIE SIND NICHT SICHER", en: "SPOILER: YOU ARE NOT SECURE" },
  "hero.title1": { de: "Ihre IT-Sicherheit", en: "Your IT Security" },
  "hero.title2": { de: "ist ein", en: "is a" },
  "hero.title3": { de: "Witz.", en: "Joke." },
  "hero.sub1": { de: "Wir meinen das ernst. 80% der deutschen Unternehmen sind nicht NIS-2 compliant. Die BSI-Frist ist ", en: "We mean it. 80% of German companies are not NIS-2 compliant. The BSI deadline has " },
  "hero.sub_expired": { de: "abgelaufen", en: "expired" },
  "hero.sub2": { de: ". Das Bußgeld: ", en: ". The fine: " },
  "hero.sub3": { de: "bis zu 10 Mio. €", en: "up to 10 million €" },
  "hero.sarcasm": { de: "Aber klar, Ihr IT-Admin macht das schon. Bis er kündigt.", en: "Sure, your IT admin has it covered. Until they quit." },
  "hero.cta1": { de: "JETZT AUFWACHEN", en: "WAKE UP NOW" },
  "hero.cta2": { de: "DIE UNBEQUEME WAHRHEIT", en: "THE UNCOMFORTABLE TRUTH" },
  "hero.scroll": { de: "SCROLLEN", en: "SCROLL" },

  // ShockStats
  "stats.tag": { de: "// Die Zahlen lügen nicht", en: "// The numbers don't lie" },
  "stats.title1": { de: "Das ist kein Panikmache.", en: "This is not scaremongering." },
  "stats.title2": { de: "Das sind Fakten.", en: "These are facts." },
  "stats.fine_label": { de: "MAXIMALES BUSSGELD", en: "MAXIMUM FINE" },
  "stats.fine_sub": { de: "// Oder 2% Ihres Jahresumsatzes. Was mehr wehtut.", en: "// Or 2% of your annual revenue. Whichever hurts more." },
  "stats.companies_label": { de: "BETROFFENE UNTERNEHMEN", en: "AFFECTED COMPANIES" },
  "stats.companies_sub": { de: "// In 18 Sektoren. Ja, Ihrer ist dabei.", en: "// Across 18 sectors. Yes, yours is included." },
  "stats.noncompliant_label": { de: "NICHT COMPLIANT", en: "NOT COMPLIANT" },
  "stats.noncompliant_sub": { de: "// Die Mehrheit hofft einfach, nicht erwischt zu werden.", en: "// The majority just hopes they won't get caught." },
  "stats.deadline_label": { de: "BSI-FRIST ÜBRIG", en: "BSI DEADLINE LEFT" },
  "stats.deadline_sub": { de: "// Abgelaufen am 6. März 2026. Überraschung.", en: "// Expired on March 6, 2026. Surprise." },
  "stats.quote": { de: "'Ach, das betrifft uns bestimmt nicht.'", en: '"Oh, that surely doesn\'t apply to us."' },
  "stats.quote_attr": { de: "— Jedes zweite Unternehmen, bevor es den Bußgeldbescheid bekommt.", en: "— Every other company, before they receive the fine notice." },

  // RealityCheck
  "reality.tag": { de: "// Reality Check", en: "// Reality Check" },
  "reality.title1": { de: "Was Sie sich", en: "What you" },
  "reality.title2": { de: "einreden.", en: "tell yourself." },
  "reality.title3": { de: "Und was ", en: "And what " },
  "reality.title4": { de: "wirklich", en: "really" },
  "reality.title5": { de: " passiert.", en: " happens." },
  "reality.image_caption": { de: "// Das hier passiert gerade. Irgendwo. Vielleicht bei Ihnen.", en: "// This is happening right now. Somewhere. Maybe at your company." },
  "reality.believe": { de: "WAS SIE GLAUBEN:", en: "WHAT YOU BELIEVE:" },
  "reality.truth": { de: "DIE REALITÄT:", en: "THE REALITY:" },
  "reality.myth1": { de: "'Unser IT-Admin kümmert sich um die Sicherheit.'", en: '"Our IT admin takes care of security."' },
  "reality.fact1": { de: "Ihr IT-Admin hat 47 offene Tickets, verwaltet 200 Endgeräte und hat seit 3 Jahren keine Weiterbildung gemacht. Er ist kein Security-Experte — er ist überfordert.", en: "Your IT admin has 47 open tickets, manages 200 endpoints, and hasn't had training in 3 years. They're not a security expert — they're overwhelmed." },
  "reality.myth2": { de: "'Wir sind zu klein, um gehackt zu werden.'", en: '"We\'re too small to be hacked."' },
  "reality.fact2": { de: "62% aller Cyberangriffe treffen KMUs. Gerade weil Sie denken, Sie seien zu klein, sind Sie ein leichtes Ziel.", en: "62% of all cyberattacks target SMEs. Precisely because you think you're too small, you're an easy target." },
  "reality.myth3": { de: "'Wir haben eine Firewall, das reicht.'", en: '"We have a firewall, that\'s enough."' },
  "reality.fact3": { de: "Eine Firewall ohne Monitoring ist wie eine Haustür ohne Schloss — sie sieht nur so aus, als würde sie schützen.", en: "A firewall without monitoring is like a front door without a lock — it just looks like it's protecting you." },
  "reality.myth4": { de: "'NIS-2 betrifft uns nicht.'", en: '"NIS-2 doesn\'t apply to us."' },
  "reality.fact4": { de: "29.500 Unternehmen in 18 Sektoren. Wenn Sie mehr als 50 Mitarbeiter oder 10 Mio. € Umsatz haben: Doch, betrifft Sie.", en: "29,500 companies across 18 sectors. If you have more than 50 employees or €10M revenue: Yes, it applies to you." },
  "reality.spoiler_title": { de: "Spoiler Alert:", en: "Spoiler Alert:" },
  "reality.spoiler_text": { de: "Sie könnten auch einfach warten, bis Sie gehackt werden. Oder Sie lassen uns in 48 Stunden prüfen, wo Sie stehen. Für 990 €. Das ist weniger als ein Tag Betriebsausfall kostet.", en: "You could just wait until you get hacked. Or let us check where you stand in 48 hours. For €990. That's less than one day of downtime costs." },
  "reality.spoiler_cta": { de: "SECURITY QUICK CHECK ANSEHEN →", en: "VIEW SECURITY QUICK CHECK →" },

  // NIS-2
  "nis2.badge": { de: "BSI-FRIST: ABGELAUFEN SEIT 6. MÄRZ 2026", en: "BSI DEADLINE: EXPIRED SINCE MARCH 6, 2026" },
  "nis2.title1": { de: "NIS-2 ist kein", en: "NIS-2 is not a" },
  "nis2.title2": { de: "'irgendwann mal'", en: '"someday"' },
  "nis2.title3": { de: "Thema mehr.", en: "topic anymore." },
  "nis2.text1_pre": { de: "Das NIS2-Umsetzungsgesetz gilt seit dem ", en: "The NIS2 Implementation Act has been in effect since " },
  "nis2.text1_date1": { de: "6. Dezember 2025", en: "December 6, 2025" },
  "nis2.text1_mid": { de: ". Die BSI-Registrierungsfrist lief am ", en: ". The BSI registration deadline expired on " },
  "nis2.text1_date2": { de: "6. März 2026", en: "March 6, 2026" },
  "nis2.text1_post": { de: " ab. Sie lesen das hier. Die Frist ist vorbei.", en: ". You're reading this. The deadline has passed." },
  "nis2.text2": { de: "Und nein, 'wir kümmern uns drum' ist keine Compliance-Strategie. Das BSI sieht das anders. Und die Bußgelder sind real.", en: "And no, 'we'll take care of it' is not a compliance strategy. The BSI sees it differently. And the fines are real." },
  "nis2.what_title": { de: "Was NIS-2 von Ihnen verlangt:", en: "What NIS-2 requires from you:" },
  "nis2.req1_title": { de: "RISIKOMANAGEMENT", en: "RISK MANAGEMENT" },
  "nis2.req1_desc": { de: "Systematische Bewertung und Behandlung von Cyberrisiken", en: "Systematic assessment and treatment of cyber risks" },
  "nis2.req2_title": { de: "INCIDENT REPORTING", en: "INCIDENT REPORTING" },
  "nis2.req2_desc": { de: "Meldepflicht innerhalb von 24h an das BSI", en: "Mandatory reporting to BSI within 24 hours" },
  "nis2.req3_title": { de: "SUPPLY CHAIN SECURITY", en: "SUPPLY CHAIN SECURITY" },
  "nis2.req3_desc": { de: "Sicherheitsanforderungen an Ihre gesamte Lieferkette", en: "Security requirements for your entire supply chain" },
  "nis2.req4_title": { de: "BUSINESS CONTINUITY", en: "BUSINESS CONTINUITY" },
  "nis2.req4_desc": { de: "Notfallpläne und Wiederherstellungsverfahren", en: "Emergency plans and recovery procedures" },
  "nis2.req5_title": { de: "SCHULUNGSPFLICHT", en: "TRAINING OBLIGATION" },
  "nis2.req5_desc": { de: "Regelmäßige Cybersecurity-Schulungen für alle Mitarbeiter", en: "Regular cybersecurity training for all employees" },
  "nis2.req6_title": { de: "GESCHÄFTSFÜHRERHAFTUNG", en: "CEO LIABILITY" },
  "nis2.req6_desc": { de: "Persönliche Haftung der Geschäftsführung. Ja, persönlich.", en: "Personal liability of management. Yes, personal." },
  "nis2.cta1": { de: "NIS-2 AUDIT BUCHEN — AB 4.900 €", en: "BOOK NIS-2 AUDIT — FROM €4,900" },
  "nis2.cta2": { de: "ERSTGESPRÄCH — KOSTENLOS", en: "INITIAL CONSULTATION — FREE" },
  "nis2.fact_deadline": { de: "BSI-FRIST ABGELAUFEN", en: "BSI DEADLINE EXPIRED" },
  "nis2.fact_fine": { de: "MAX. BUSSGELD", en: "MAX. FINE" },
  "nis2.fact_companies": { de: "BETROFFENE UNTERNEHMEN", en: "AFFECTED COMPANIES" },

  // Services
  "services.tag": { de: "// Was wir tun", en: "// What we do" },
  "services.title1": { de: "Keine leeren Versprechen.", en: "No empty promises." },
  "services.title2": { de: "Klare Preise. Klare Ergebnisse.", en: "Clear prices. Clear results." },
  "services.desc": { de: "Andere reden über Cybersecurity. Wir machen es. Mit 17 Experten, 20+ Jahren Erfahrung und Preisen, die wir nicht hinter 'Preis auf Anfrage' verstecken.", en: "Others talk about cybersecurity. We do it. With 17 experts, 20+ years of experience, and prices we don't hide behind 'price on request'." },
  "services.nis2_title": { de: "NIS-2 Compliance", en: "NIS-2 Compliance" },
  "services.nis2_sub": { de: "Bevor das BSI klopft.", en: "Before the BSI comes knocking." },
  "services.nis2_desc": { de: "Vollständige Gap-Analyse, Mängelliste, priorisierte Roadmap. In 14 Arbeitstagen wissen Sie, wo Sie stehen. Und wo nicht.", en: "Complete gap analysis, deficiency list, prioritized roadmap. In 14 working days you'll know where you stand. And where you don't." },
  "services.nis2_price": { de: "ab 4.900 €", en: "from €4,900" },
  "services.nis2_note": { de: "Garantie: Finden wir keine Lücke, zahlen Sie nichts.", en: "Guarantee: If we find no gaps, you pay nothing." },
  "services.pentest_title": { de: "Penetration Testing", en: "Penetration Testing" },
  "services.pentest_sub": { de: "Wir hacken Sie. Legal.", en: "We hack you. Legally." },
  "services.pentest_desc": { de: "Externer oder umfassender Pentest inkl. Social Engineering. Wir finden die Lücken, bevor es jemand anderes tut.", en: "External or comprehensive pentest incl. social engineering. We find the gaps before someone else does." },
  "services.pentest_price": { de: "ab 3.500 €", en: "from €3,500" },
  "services.pentest_note": { de: "Bonus: Kostenloser Re-Test nach 90 Tagen.", en: "Bonus: Free re-test after 90 days." },
  "services.quickcheck_title": { de: "Security Quick Check", en: "Security Quick Check" },
  "services.quickcheck_sub": { de: "48 Stunden. 990 €. Keine Ausreden.", en: "48 hours. €990. No excuses." },
  "services.quickcheck_desc": { de: "2-stündige Analyse der wichtigsten Schwachstellen mit sofortigem Ergebnisbericht. Der schnellste Weg zu wissen, wie schlimm es wirklich ist.", en: "2-hour analysis of the most critical vulnerabilities with immediate results report. The fastest way to know how bad it really is." },
  "services.quickcheck_price": { de: "990 €", en: "€990" },
  "services.quickcheck_note": { de: "Ergebnis in 48 Stunden. Nicht 48 Tagen.", en: "Results in 48 hours. Not 48 days." },
  "services.ciso_title": { de: "CISO as a Service", en: "CISO as a Service" },
  "services.ciso_sub": { de: "Ein CISO, den Sie sich leisten können.", en: "A CISO you can actually afford." },
  "services.ciso_desc": { de: "Strategische IT-Sicherheitsberatung, 8h/Monat, Board-Reporting, Incident-Koordination. Ohne 150k Jahresgehalt.", en: "Strategic IT security consulting, 8h/month, board reporting, incident coordination. Without a €150k annual salary." },
  "services.ciso_price": { de: "ab 2.490 €/Monat", en: "from €2,490/month" },
  "services.ciso_note": { de: "Ab 6 Monate. Kein Risiko, volle Expertise.", en: "From 6 months. No risk, full expertise." },
  "services.staff_title": { de: "Professional Services", en: "Professional Services" },
  "services.staff_sub": { de: "Ihr Team ist zu dünn? Unseres nicht.", en: "Your team is too thin? Ours isn't." },
  "services.staff_desc": { de: "IT-Security-Experten auf Stundenbasis. Nearshore (Europe-based) ab 65 €/h, Onshore ab 95 €/h. Verfügbar ab 48 Stunden.", en: "IT security experts on an hourly basis. Nearshore (Europe-based) from €65/h, Onshore from €95/h. Available within 48 hours." },
  "services.staff_price": { de: "ab 65 €/h", en: "from €65/h" },
  "services.staff_note": { de: "17 Experten. Einer passt zu Ihrem Problem.", en: "17 experts. One fits your problem." },
  "services.mssp_title": { de: "Managed Security (MSSP)", en: "Managed Security (MSSP)" },
  "services.mssp_sub": { de: "24/7 Überwachung. Auch wenn Sie schlafen.", en: "24/7 monitoring. Even while you sleep." },
  "services.mssp_desc": { de: "Security Monitoring, Threat Intelligence, Incident-Hotline. Weil Hacker keine Bürozeiten haben.", en: "Security monitoring, threat intelligence, incident hotline. Because hackers don't have office hours." },
  "services.mssp_price": { de: "ab 1.990 €/Monat", en: "from €1,990/month" },
  "services.mssp_note": { de: "12 Monate. Rund um die Uhr geschützt.", en: "12 months. Protected around the clock." },

  // Videos
  "videos.tag": { de: "// Sehen statt lesen", en: "// Watch instead of read" },
  "videos.title1": { de: "Zu faul zum Lesen?", en: "Too lazy to read?" },
  "videos.title2": { de: "Verstehen wir.", en: "We get it." },
  "videos.desc": { de: "Drei Videos. Drei Minuten. Danach wissen Sie mehr als 80% Ihrer Konkurrenz über IT-Sicherheit.", en: "Three videos. Three minutes. After that, you'll know more about IT security than 80% of your competitors." },
  "videos.v1_title": { de: "NIS-2: Was Sie wissen müssen", en: "NIS-2: What You Need to Know" },
  "videos.v1_sub": { de: "In unter 3 Minuten erklärt. Weil Sie keine Zeit haben, 200 Seiten EU-Richtlinie zu lesen.", en: "Explained in under 3 minutes. Because you don't have time to read 200 pages of EU directive." },
  "videos.v1_tag": { de: "NIS-2 Compliance", en: "NIS-2 Compliance" },
  "videos.v2_title": { de: "Experte in 48 Stunden", en: "Expert in 48 Hours" },
  "videos.v2_sub": { de: "Sie brauchen einen Security-Experten? Gestern? Wir liefern in 48 Stunden.", en: "Need a security expert? Yesterday? We deliver in 48 hours." },
  "videos.v2_tag": { de: "Staff Augmentation", en: "Staff Augmentation" },
  "videos.v3_title": { de: "Security Quick Check", en: "Security Quick Check" },
  "videos.v3_sub": { de: "990 €. 48 Stunden. Sie wissen, wo Sie stehen. Kein Bullshit.", en: "€990. 48 hours. You know where you stand. No BS." },
  "videos.v3_tag": { de: "Quick Check", en: "Quick Check" },

  // Pricing
  "pricing.tag": { de: "// Preise — Ja, echte Preise", en: "// Pricing — Yes, real prices" },
  "pricing.title1": { de: "Transparenz ist sexy.", en: "Transparency is sexy." },
  "pricing.title2": { de: "Andere verstecken ihre Preise. Wir nicht.", en: "Others hide their prices. We don't." },
  "pricing.desc": { de: "Keine 'Preis auf Anfrage'-Spielchen. Keine versteckten Kosten. Sie wissen vorher, was es kostet. Radikal, oder?", en: "No 'price on request' games. No hidden costs. You know upfront what it costs. Radical, right?" },
  "pricing.fixed_title": { de: "FESTPREIS-PAKETE", en: "FIXED-PRICE PACKAGES" },
  "pricing.popular": { de: "BELIEBTESTE WAHL", en: "MOST POPULAR" },
  "pricing.quickcheck_name": { de: "Security Quick Check", en: "Security Quick Check" },
  "pricing.quickcheck_sub": { de: "Der Einstieg. Keine Ausreden.", en: "The starting point. No excuses." },
  "pricing.quickcheck_price": { de: "990 €", en: "€990" },
  "pricing.quickcheck_unit": { de: "einmalig", en: "one-time" },
  "pricing.quickcheck_f1": { de: "2-stündige Schwachstellenanalyse", en: "2-hour vulnerability analysis" },
  "pricing.quickcheck_f2": { de: "Sofortiger Ergebnisbericht", en: "Immediate results report" },
  "pricing.quickcheck_f3": { de: "Priorisierte Handlungsempfehlungen", en: "Prioritized action recommendations" },
  "pricing.quickcheck_f4": { de: "Ergebnis in 48 Stunden", en: "Results in 48 hours" },
  "pricing.quickcheck_cta": { de: "QUICK CHECK BUCHEN", en: "BOOK QUICK CHECK" },
  "pricing.audit_name": { de: "CyberSchild Audit (NIS-2)", en: "CyberShield Audit (NIS-2)" },
  "pricing.audit_sub": { de: "Für die, die es ernst meinen.", en: "For those who are serious." },
  "pricing.audit_price": { de: "4.900 €", en: "€4,900" },
  "pricing.audit_f1": { de: "Vollständige NIS-2 Gap-Analyse", en: "Complete NIS-2 gap analysis" },
  "pricing.audit_f2": { de: "Detaillierte Mängelliste", en: "Detailed deficiency list" },
  "pricing.audit_f3": { de: "Priorisierte Roadmap", en: "Prioritized roadmap" },
  "pricing.audit_f4": { de: "Management-Summary", en: "Management summary" },
  "pricing.audit_f5": { de: "Ergebnis in 14 Arbeitstagen", en: "Results in 14 working days" },
  "pricing.audit_f6": { de: "Garantie: Keine Lücke = kein Geld", en: "Guarantee: No gaps = no charge" },
  "pricing.audit_cta": { de: "AUDIT STARTEN", en: "START AUDIT" },
  "pricing.komplett_name": { de: "NIS-2 Komplett", en: "NIS-2 Complete" },
  "pricing.komplett_sub": { de: "Audit + Umsetzung. Alles aus einer Hand.", en: "Audit + implementation. All from one source." },
  "pricing.komplett_price": { de: "9.900 €", en: "€9,900" },
  "pricing.komplett_f1": { de: "Alles aus dem CyberSchild Audit", en: "Everything from the CyberShield Audit" },
  "pricing.komplett_f2": { de: "Komplette Umsetzungsbegleitung", en: "Complete implementation support" },
  "pricing.komplett_f3": { de: "Richtlinien & Dokumentation", en: "Policies & documentation" },
  "pricing.komplett_f4": { de: "Mitarbeiterschulungen", en: "Employee training" },
  "pricing.komplett_f5": { de: "BSI-Registrierung", en: "BSI registration" },
  "pricing.komplett_f6": { de: "Abschlusszertifikat", en: "Completion certificate" },
  "pricing.komplett_cta": { de: "KOMPLETT-PAKET BUCHEN", en: "BOOK COMPLETE PACKAGE" },
  "pricing.pentest_title": { de: "PENTESTING", en: "PENTESTING" },
  "pricing.pentest_sub": { de: "// Wir hacken Sie. Damit es kein anderer tut.", en: "// We hack you. So nobody else does." },
  "pricing.pentest_starter": { de: "PenTest Starter", en: "PenTest Starter" },
  "pricing.pentest_pro": { de: "PenTest Professional", en: "PenTest Professional" },
  "pricing.pentest_starter_price": { de: "3.500 €", en: "€3,500" },
  "pricing.pentest_pro_price": { de: "8.900 €", en: "€8,900" },
  "pricing.pentest_starter_time": { de: "Lieferzeit: 21 Arbeitstage", en: "Delivery: 21 working days" },
  "pricing.pentest_pro_time": { de: "Lieferzeit: 30 Arbeitstage", en: "Delivery: 30 working days" },
  "pricing.pentest_s_f1": { de: "Externer Penetrationstest", en: "External penetration test" },
  "pricing.pentest_s_f2": { de: "Web-App oder Netzwerk", en: "Web app or network" },
  "pricing.pentest_s_f3": { de: "Executive Report", en: "Executive report" },
  "pricing.pentest_s_f4": { de: "Technischer Detailbericht", en: "Technical detail report" },
  "pricing.pentest_s_f5": { de: "Kostenloser Re-Test (90 Tage)", en: "Free re-test (90 days)" },
  "pricing.pentest_p_f1": { de: "Umfassender Pentest (intern + extern)", en: "Comprehensive pentest (internal + external)" },
  "pricing.pentest_p_f2": { de: "Social Engineering", en: "Social engineering" },
  "pricing.pentest_p_f3": { de: "Physischer Zugangstest", en: "Physical access test" },
  "pricing.pentest_p_f4": { de: "Executive + technischer Report", en: "Executive + technical report" },
  "pricing.pentest_p_f5": { de: "Kostenloser Re-Test (90 Tage)", en: "Free re-test (90 days)" },
  "pricing.pentest_p_f6": { de: "Präsentation für Management", en: "Management presentation" },
  "pricing.pentest_cta": { de: "PENTEST ANFRAGEN", en: "REQUEST PENTEST" },
  "pricing.abo_title": { de: "ABO-MODELLE", en: "SUBSCRIPTION MODELS" },
  "pricing.abo_sub": { de: "// Dauerhafter Schutz. Weil Hacker keine Einmalzahlung akzeptieren.", en: "// Ongoing protection. Because hackers don't accept one-time payments." },
  "pricing.ciso_name": { de: "CISO as a Service", en: "CISO as a Service" },
  "pricing.ciso_price_val": { de: "ab 2.490 €", en: "from €2,490" },
  "pricing.ciso_unit": { de: "/Monat", en: "/month" },
  "pricing.ciso_time": { de: "Laufzeit: 6 Monate", en: "Duration: 6 months" },
  "pricing.ciso_f1": { de: "Strategische IT-Sicherheitsberatung", en: "Strategic IT security consulting" },
  "pricing.ciso_f2": { de: "8h/Monat dedizierte Beratung", en: "8h/month dedicated consulting" },
  "pricing.ciso_f3": { de: "Board-Reporting", en: "Board reporting" },
  "pricing.ciso_f4": { de: "Incident-Koordination", en: "Incident coordination" },
  "pricing.nis2care_name": { de: "NIS-2 Compliance Care", en: "NIS-2 Compliance Care" },
  "pricing.nis2care_price": { de: "ab 990 €", en: "from €990" },
  "pricing.nis2care_time": { de: "Laufzeit: 12 Monate", en: "Duration: 12 months" },
  "pricing.nis2care_f1": { de: "Monatliche Compliance-Überwachung", en: "Monthly compliance monitoring" },
  "pricing.nis2care_f2": { de: "Mitarbeiterschulungen", en: "Employee training" },
  "pricing.nis2care_f3": { de: "Richtlinien-Updates", en: "Policy updates" },
  "pricing.nis2care_f4": { de: "Audit-Vorbereitung", en: "Audit preparation" },
  "pricing.mssp_basic_name": { de: "MSSP Basic", en: "MSSP Basic" },
  "pricing.mssp_basic_price": { de: "ab 1.990 €", en: "from €1,990" },
  "pricing.mssp_basic_time": { de: "Laufzeit: 12 Monate", en: "Duration: 12 months" },
  "pricing.mssp_basic_f1": { de: "24/7 Security Monitoring", en: "24/7 security monitoring" },
  "pricing.mssp_basic_f2": { de: "Monatlicher Statusbericht", en: "Monthly status report" },
  "pricing.mssp_basic_f3": { de: "Incident-Hotline", en: "Incident hotline" },
  "pricing.mssp_pro_name": { de: "MSSP Professional", en: "MSSP Professional" },
  "pricing.mssp_pro_price": { de: "ab 3.990 €", en: "from €3,990" },
  "pricing.mssp_pro_time": { de: "Laufzeit: 12 Monate", en: "Duration: 12 months" },
  "pricing.mssp_pro_f1": { de: "Alles aus MSSP Basic", en: "Everything from MSSP Basic" },
  "pricing.mssp_pro_f2": { de: "Threat Intelligence", en: "Threat intelligence" },
  "pricing.mssp_pro_f3": { de: "Quartalsweiser Pentest", en: "Quarterly pentest" },
  "pricing.mssp_pro_f4": { de: "Dedizierter Ansprechpartner", en: "Dedicated contact person" },
  "pricing.staff_title": { de: "PROFESSIONAL SERVICES", en: "PROFESSIONAL SERVICES" },
  "pricing.staff_sub": { de: "// Ihr Team braucht Verstärkung? Wir haben 17 Experten. Einer passt.", en: "// Your team needs reinforcement? We have 17 experts. One fits." },
  "pricing.nearshore_name": { de: "Nearshore (Europe-based)", en: "Nearshore (Europe-based)" },
  "pricing.nearshore_desc": { de: "IT-Security-Experten, remote", en: "IT security experts, remote" },
  "pricing.nearshore_price": { de: "65–95 €", en: "€65–95" },
  "pricing.nearshore_unit": { de: "/Stunde", en: "/hour" },
  "pricing.nearshore_avail": { de: "Verfügbar ab 48 Stunden", en: "Available within 48 hours" },
  "pricing.onshore_name": { de: "Onshore (Deutschland)", en: "Onshore (Germany)" },
  "pricing.onshore_desc": { de: "IT-Security-Experten, vor Ort oder remote", en: "IT security experts, on-site or remote" },
  "pricing.onshore_price": { de: "95–135 €", en: "€95–135" },
  "pricing.onshore_avail": { de: "Verfügbar ab 1 Woche", en: "Available within 1 week" },
  "pricing.netto_note": { de: "// Alle Preise netto zzgl. MwSt. Keine versteckten Kosten. Versprochen.", en: "// All prices net plus VAT. No hidden costs. Promised." },

  // NIS-2 Checklist Download
  "checklist.tag": { de: "// Kostenloser Download", en: "// Free download" },
  "checklist.title1": { de: "NIS-2 Checkliste.", en: "NIS-2 Checklist." },
  "checklist.title2": { de: "Kostenlos. Sofort.", en: "Free. Instant." },
  "checklist.desc": { de: "37 Punkte, die Sie abhaken müssen. Laden Sie unsere NIS-2 Compliance-Checkliste herunter und prüfen Sie selbst, wo Sie stehen.", en: "37 items you need to check off. Download our NIS-2 compliance checklist and see for yourself where you stand." },
  "checklist.name_label": { de: "Vollständiger Name", en: "Full Name" },
  "checklist.name_placeholder": { de: "Max Mustermann", en: "John Smith" },
  "checklist.email_label": { de: "Geschäftliche E-Mail-Adresse", en: "Business Email Address" },
  "checklist.email_placeholder": { de: "m.mustermann@firma.de", en: "j.smith@company.com" },
  "checklist.email_error": { de: "Bitte verwenden Sie Ihre geschäftliche E-Mail-Adresse (keine öffentlichen Anbieter wie Gmail, GMX, etc.)", en: "Please use your business email address (no public providers like Gmail, GMX, etc.)" },
  "checklist.name_error": { de: "Bitte geben Sie Ihren vollständigen Namen ein.", en: "Please enter your full name." },
  "checklist.submit": { de: "CHECKLISTE HERUNTERLADEN", en: "DOWNLOAD CHECKLIST" },
  "checklist.privacy": { de: "Ihre Daten werden vertraulich behandelt und nicht an Dritte weitergegeben.", en: "Your data will be treated confidentially and not shared with third parties." },
  "checklist.features": { de: "37 Prüfpunkte|5 Kategorien|Sofortiger Download", en: "37 checkpoints|5 categories|Instant download" },

  // Team
  "team.tag": { de: "// Wer wir sind", en: "// Who we are" },
  "team.title1": { de: "17 Experten.", en: "17 Experts." },
  "team.title2": { de: "20+ Jahre.", en: "20+ Years." },
  "team.title3": { de: "Null Toleranz für Bullshit.", en: "Zero tolerance for BS." },
  "team.p1": { de: "B2CyberSec ist kein Startup mit drei Leuten und einem LinkedIn-Profil. Wir sind 17 IT-Security-Spezialisten mit über 20 Jahren Erfahrung. Sitz in Augsburg. Einsatzgebiet: ganz Deutschland.", en: "B2CyberSec is not a startup with three people and a LinkedIn profile. We are 17 IT security specialists with over 20 years of experience. Based in Augsburg. Operating area: all of Germany." },
  "team.p2_pre": { de: "Wir machen keine PowerPoint-Präsentationen über Cybersecurity. Wir ", en: "We don't make PowerPoint presentations about cybersecurity. We " },
  "team.p2_bold": { de: "machen", en: "do" },
  "team.p2_post": { de: " Cybersecurity. Pentests, NIS-2 Audits, CISO-Beratung, 24/7 Monitoring. Hands-on, nicht Hands-off.", en: " cybersecurity. Pentests, NIS-2 audits, CISO consulting, 24/7 monitoring. Hands-on, not hands-off." },
  "team.p3": { de: "// Und ja, wir können auch innerhalb von 48 Stunden einen Experten bereitstellen. Weil wir wissen, dass Cyberangriffe nicht auf Ihren Terminkalender Rücksicht nehmen.", en: "// And yes, we can also provide an expert within 48 hours. Because we know that cyberattacks don't care about your calendar." },
  "team.stat1_num": { de: "17", en: "17" },
  "team.stat1_label": { de: "Security-Experten", en: "Security Experts" },
  "team.stat1_sub": { de: "Kein Freelancer-Netzwerk", en: "No freelancer network" },
  "team.stat2_num": { de: "20+", en: "20+" },
  "team.stat2_label": { de: "Jahre Erfahrung", en: "Years of Experience" },
  "team.stat2_sub": { de: "In IT-Security & Netzwerk", en: "In IT security & network" },
  "team.stat3_num": { de: "48h", en: "48h" },
  "team.stat3_label": { de: "Experte verfügbar", en: "Expert Available" },
  "team.stat3_sub": { de: "Wenn es brennt", en: "When it's urgent" },
  "team.stat4_num": { de: "24/7", en: "24/7" },
  "team.stat4_label": { de: "Monitoring", en: "Monitoring" },
  "team.stat4_sub": { de: "Auch Weihnachten", en: "Even on Christmas" },
  "team.stat5_num": { de: "18", en: "18" },
  "team.stat5_label": { de: "Sektoren abgedeckt", en: "Sectors Covered" },
  "team.stat5_sub": { de: "NIS-2 Compliance", en: "NIS-2 Compliance" },
  "team.stat6_num": { de: "100%", en: "100%" },
  "team.stat6_label": { de: "Transparente Preise", en: "Transparent Prices" },
  "team.stat6_sub": { de: "Kein 'Preis auf Anfrage'", en: "No 'price on request'" },

  // Contact
  "contact.tag": { de: "// Der letzte Abschnitt. Ihre Entscheidung.", en: "// The last section. Your decision." },
  "contact.title1": { de: "Sie haben zwei", en: "You have two" },
  "contact.title2": { de: "Optionen.", en: "options." },
  "contact.optionA_title": { de: "Option A: Nichts tun", en: "Option A: Do nothing" },
  "contact.optionA_1": { de: "→ Weiter hoffen, dass es Sie nicht trifft", en: "→ Keep hoping it won't happen to you" },
  "contact.optionA_2": { de: "→ BSI-Bußgeld riskieren (bis 10 Mio. €)", en: "→ Risk BSI fines (up to €10M)" },
  "contact.optionA_3": { de: "→ Beim nächsten Ransomware-Angriff improvisieren", en: "→ Improvise during the next ransomware attack" },
  "contact.optionA_4": { de: "→ Ihrem IT-Admin die Schuld geben", en: "→ Blame your IT admin" },
  "contact.optionA_5": { de: "→ Diese Seite schließen und vergessen", en: "→ Close this page and forget about it" },
  "contact.optionA_note": { de: "// Statistisch die beliebteste Wahl. Leider.", en: "// Statistically the most popular choice. Unfortunately." },
  "contact.optionB_title": { de: "Option B: Jetzt handeln", en: "Option B: Act now" },
  "contact.optionB_1": { de: "15-Minuten Erstgespräch — kostenlos, unverbindlich", en: "15-minute initial consultation — free, no obligation" },
  "contact.optionB_2": { de: "Security Quick Check in 48h — ab 990 €", en: "Security Quick Check in 48h — from €990" },
  "contact.optionB_3": { de: "NIS-2 Compliance in 14 Tagen — ab 4.900 €", en: "NIS-2 Compliance in 14 days — from €4,900" },
  "contact.optionB_4": { de: "Endlich ruhig schlafen", en: "Finally sleep peacefully" },
  "contact.optionB_cta": { de: "Termin buchen", en: "Book appointment" },
  "contact.ps": { de: "// P.S. Wenn Sie bis hierhin gescrollt haben und immer noch nichts tun — wir können Ihnen auch nicht helfen. Aber wir haben es versucht.", en: "// P.S. If you've scrolled this far and still won't act — we can't help you either. But we tried." },

  // Footer
  "footer.services": { de: "Services", en: "Services" },
  "footer.contact": { de: "Kontakt", en: "Contact" },
  "footer.book": { de: "Termin buchen (Calendly)", en: "Book appointment (Calendly)" },
  "footer.rights": { de: "Alle Rechte vorbehalten.", en: "All rights reserved." },
  "footer.impressum": { de: "Impressum", en: "Legal Notice" },
  "footer.datenschutz": { de: "Datenschutz", en: "Privacy Policy" },
  "footer.tagline": { de: "IT Security Solutions & Services.", en: "IT Security Solutions & Services." },
  "footer.location": { de: "Augsburg. Deutschland. Seit 20+ Jahren.", en: "Augsburg. Germany. For 20+ years." },

  // Calendly section
  "calendly.tag": { de: "// Termin buchen", en: "// Book appointment" },
  "calendly.title1": { de: "Reden wir.", en: "Let's talk." },
  "calendly.title2": { de: "15 Minuten. Kostenlos.", en: "15 minutes. Free." },
  "calendly.desc": { de: "Buchen Sie direkt einen Termin. Kein Vertriebsgespräch, keine PowerPoint. Nur eine ehrliche Einschätzung Ihrer Situation.", en: "Book an appointment directly. No sales pitch, no PowerPoint. Just an honest assessment of your situation." },
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("de");

  const t = useCallback(
    (key: string): string => {
      const entry = translations[key];
      if (!entry) return key;
      return entry[lang] || entry.de || key;
    },
    [lang]
  );

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
